### PR TITLE
Prevent empty `Dependencies` from being added to `dependency_types`

### LINKED ISSUE #289: TypeList recursion limit
**Describe the bug**

Since the upgrade from 7.1.1 to 8.1.0, I'm getting recursion limit errors

```
error[E0275]: overflow evaluating the requirement `impl TypeList well-formed`
```

or

```
reached the recursion limit while instantiating `<(((((..., ...), ...), ...), ...), ...) as TypeList>::for_each::<...>`
```

(on a crate that depends on a crate with `#![recursion_limit = "..."]`)

**To Reproduce**

Derive TS on an enum with 130+ fields, for example:

```rs
#[derive(Debug, ts_rs::TS)]
#[ts(export)]
pub enum Iso4217CurrencyCode {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SPL,
    // SRD,
    // STN,
    // SVC,
    // SYP,
    // SZL,
    // THB,
    // TJS,
    // TMT,
    // TND,
    // TOP,
    // TRY,
    // TTD,
    // TVD,
    // TWD,
    // TZS,
    // UAH,
    // UGX,
    USD,
    // UYU,
    // UZS,
    // VEF,
    // VND,
    // VUV,
    // WST,
    // XAF,
    // XCD,
    // XDR,
    // XOF,
    // XPF,
    // YER,
    // ZAR,
    // ZMW,
    // ZWD,
}

fn main() {
    println!("{:?}", Iso4217CurrencyCode::USD)
}
```

if you comment out some variants, it compiles. There is a point where it stops compiling (the default recursion limit is [128](https://doc.rust-lang.org/reference/attributes/limits.html))

**Expected behavior**

**Screenshots**

**Version**
8.1.0

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
## Goal

A type with 128+ variants/fields will cause a massive `TypeList` to be generated, even if all of its items are `()`. This can cause an overflow before the type actually has 128+ dependencies
Closes #289

## Changes

I added a check to `Dependencies::append` so that it only appends if `other.dependencies` is not empty

## Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/Aleph-Alpha/ts-rs/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by NyxCode** [comment]
Oh, that's great! Didn't think that was enough to get #289 fixed!  

Do you see any limitations with this as-is? What would we need to provoke the error now?

**Comment by escritorio-gustavo** [comment]
> Do you see any limitations with this as-is? What would we need to provoke the error now?

I _think_ we actually need 128+ dependencies on the same type, but I'm not sure about that yet

**Comment by NyxCode** [comment]
I think we should then merge this fix, and think about more complicated solutions once someone has a usecase for such an abomination 😅

**Comment by escritorio-gustavo** [comment]
> Scratch that. Just make all the variants `Variant(String)` lol

That'll generate this in `dependency_types`

```rs
{
    use ::ts_rs::typelist::TypeList;
    ().extend({
        use ::ts_rs::typelist::TypeList;
        ().push::<String>()
            .extend(<String as ::ts_rs::TS>::generics())
    })
    .extend({
        use ::ts_rs::typelist::TypeList;
        ().push::<String>()
            .extend(<String as ::ts_rs::TS>::generics())
    })
    // Repeat this a bunch more times...
    .extend({
        use ::ts_rs::typelist::TypeList;
        ().push::<String>()
            .extend(<String as ::ts_rs::TS>::generics())
    })
}
```

**Comment by NyxCode** [comment]
Ah, I see! I'll prepare a PR to de-duplicate the dependencies based on their path. So `std::string::String` and `String` will still show up as separate items in the `TypeList`, but that's okay, I think.  

This is somewhat orthogonal to generating a separate type implementing `TypeList` - If we do that at some point, the de-duplication will still be usefull, saving time when generating imports.

**Comment by kamadorueda** [comment]
Something like this would work to dedup dependencies

```diff
diff --git a/macros/src/deps.rs b/macros/src/deps.rs
index b99c49f..ea31bfd 100644
--- a/macros/src/deps.rs
+++ b/macros/src/deps.rs
@@ -1,3 +1,5 @@
+use std::collections::HashSet;
+
 use proc_macro2::TokenStream;
 use quote::{quote, ToTokens};
 use syn::{Path, Type};
@@ -5,6 +7,8 @@ use syn::{Path, Type};
 pub struct Dependencies {
     dependencies: Vec<TokenStream>,
     crate_rename: Path,
+    seen_append: HashSet<Type>,
+    seen_push: HashSet<Type>,
     pub types: Vec<Type>,
 }
 
@@ -12,12 +16,19 @@ impl Dependencies {
     pub fn new(crate_rename: Path) -> Self {
         Self {
             dependencies: Vec::default(),
+            seen_append: HashSet::default(),
+            seen_push: HashSet::default(),
             crate_rename,
             types: Vec::default(),
         }
     }
     /// Adds all dependencies from the given type
     pub fn append_from(&mut self, ty: &Type) {
+        if self.seen_append.contains(&ty) {
+            return;
+        }
+        self.seen_append.insert(ty.clone());
+
         let crate_rename = &self.crate_rename;
         self. dependencies
             .push(quote![.extend(<#ty as #crate_rename::TS>::dependency_types())]);
@@ -26,6 +37,11 @@ impl Dependencies {
 
     /// Adds the given type.
     pub fn push(&mut self, ty: &Type) {
+        if self.seen_push.contains(&ty) {
+            return;
+        }
+        self.seen_push.insert(ty.clone());
+
         let crate_rename = &self.crate_rename;
         self.dependencies.push(quote![.push::<#ty>()]);
         self.dependencies.push(quote![
@@ -35,8 +51,19 @@ impl Dependencies {
     }
 
     pub fn append(&mut self, mut other: Dependencies) {
-        self.dependencies.push(quote![.extend(#other)]);
-        self.types.append(&mut other.types);
+        if self.seen_append == other.seen_append && self.seen_push == other.seen_push {
+            return;
+        }
+
+        self.seen_append.extend(other.seen_append.clone());
+        self.seen_push.extend(other.seen_push.clone());
+
+        if !other.dependencies.is_empty() {
+            self.dependencies.push(quote![.extend(#other)]);
+        }
+        if !other.types.is_empty() {
+            self.types.append(&mut other.types);
+        }
     }
 }
 
@@ -44,6 +71,7 @@ impl ToTokens for Dependencies {
     fn to_tokens(&self, tokens: &mut TokenStream) {
         let crate_rename = &self.crate_rename;
         let lines = &self.dependencies;
+
         tokens.extend(quote![{
             use #crate_rename::typelist::TypeList;
             ()#(#lines)*
```

it passes the tests and works with big enums like `enum test { A(X), B(X), ... }` where X repeats a lot

it honestly feels ugly though, I think changing the type signature of Dependencies to use a HashSet instead of a Vec would be way cleaner. This is not possible today as it uses TokenStream, but since in the end everything that goes into dependencies is "extend by dependency types", "push type", and "extend by generics of type", I think we could make dependencies be a HashSet of an enum with 3 variants, and delay the actual conversion to TokenStream just before it's needed by ToTokens

**Comment by NyxCode** [comment]
@kamadorueda I had the same idea and implemented something similar in #292. It needs some cleanup, but it seems to work nicely.

**Comment by kamadorueda** [comment]
@NyxCode https://github.com/Aleph-Alpha/ts-rs/pull/293
